apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-legacy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-go-app-legacy
  template:
    metadata:
      labels:
        app: my-go-app-legacy
    spec:
      containers:
        - name: my-go-app-legacy
          image: europe-docker.pkg.dev/my-holded-test-project/my-go-app/my-go-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-app-legacy
spec:
  selector:
    app: my-go-app-legacy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: my-go-app-legacy-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: my-go-app-legacy
#  minReplicas: 3
#  maxReplicas: 10
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50
---        
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-go-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-go-app-legacy
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: http_requests
          selector:
            matchLabels:
              method: "GET"
        target:
          type: Value
          value: "100"